language: rust

sudo: false

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

env:
  # Libraries
  - DAY=intcode
  # Days
  - DAY=day1
  - DAY=day2
  - DAY=day3
  - DAY=day4
script:
  - cargo test --verbose --manifest-path=$DAY/Cargo.toml