language: rust

sudo: false

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

env:
  - DAY=day1

script:
  - cargo build --verbose --manifest-path=$DAY/Cargo.toml
  - cargo test --manifest-path=$DAY/Cargo.toml