language: rust

sudo: false

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

  jobs:
    include:
    - name: "Day 1"
      env: DAY=day1

script:
  - cargo build --test --verbose --manifest-path=$DAY
  - cargo test --manifest-path=$DAY